### ISSUE TITLE
graph requires a different `scope` than Azure management

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1516]
error:

```
ERROR: failed to create or update service principal: failed retrieving application list, failed executing request: http call(https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token)(POST) error: reply status code was 400:
{"error":"invalid_grant","error_description":"AADSTS50158: External security challenge not satisfied. User will be redirected to another page or authentication provider to satisfy additional authentication challenges.\r\nTrace ID: 9a05d8d1-903d-483a-974c-caf8a8a68d02\r\nCorrelation ID: 4d0e314e-78bc-489c-aea8-8ba05bf29772\r\nTimestamp: 2023-02-07 22:34:24Z","error_codes":[50158],"timestamp":"2023-02-07 22:34:24Z","trace_id":"9a05d8d1-903d-483a-974c-caf8a8a68d02","correlation_id":"4d0e314e-78bc-489c-aea8-8ba05bf29772","error_uri":"https://login.microsoftonline.com/error?code=50158","suberror":"basic_action"}
```

To repro:
** Using daily or building from source:
- azd login (use a `@Microsoft` account)
- azd init (pick any template, any sub and location)
- azd pipeline config  ( pick create new private repo or use existing, it doesn't matter)

![image](https://user-images.githubusercontent.com/24213737/217382483-844708a5-b836-4dc4-9c15-623b07b2e5da.png)

This step fails

*Note:  This does not happen with personal accounts or other Office365 accounts.

**Comment by vhvb1989** [comment]
happening on current version as well

azd version
azd version 0.5.0-beta.3 (commit 1c23678aade587d5b9685a256a3c1d2d7f4b42e0)

**Comment by rajeshkamal5050** [comment]
@v-xuto can you try reproducing this?

**Comment by vhvb1989** [comment]
This was on my account only.
Fixed it after trying to create a service principal using `az` and the error from `az` suggested to run `az login --scope <msft graph url>` and after that it worked.  Then I logged in to `azd` and everything worked.

@weikanglim @ellismg . azd should provide the same error message and request a `login` plus scope with msgraph for this error. Something like this:

```
│ Error: building account: getting authenticated object ID: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: AADSTS530003: Your device is required to be managed to access this resource.
│ Trace ID: 50e2295c-c586-4eea-XXXX-0CCXXXXX869e701
│ Correlation ID: XXXXXXX-6a02-4a99-94cb-7f29c5573ec9
│ Timestamp: 2023-02-08 19:30:15Z
│ To re-authenticate, please run:
│ az login --scope https://graph.microsoft.com//.default
```

This will eventually reach other folks out there,

**Comment by weikanglim** [comment]
@vhvb1989 I have #1571 out that should help with this. Recommend giving it a shot when you hit this error another time.

I'm still not really happy with the solution. It seems directing users to run `login` every time they hit an authorization (not authentication issue) is rather silly. I suspect we want to include this an automatic prompt similar to what is suggested in #1391

**Comment by rajeshkamal5050** [comment]
@weikanglim @vhvb1989 There are many issues floating around on the login scope/oid. Closing this as a duplicate of #1758
