### ISSUE TITLE
azd should honor NO_COLOR environment variable

### ISSUE THREAD

**Issue by karolz-ms** [Azure/azure-dev#348]
There should be a way with `azd` to suppress the use of color output, and the de-facto industry standard seems to be https://no-color.org/

**Comment by Austinauth** [comment]
This issue should have been resolved with the latest release if the color variables are working correctly. @vhvb1989 @wallace can you confirm? 

To guarantee accessibility all of our colors should be defined as variables, defaulting to the [ANSI Defined color presets](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) of the environment (vscode, terminal, etc.).

**Comment by savannahostrowski** [comment]
@wbreza and @vhvb1989 gentle ping here - any info on this?

**Comment by karolz-ms** [comment]
I just tried with the bits built yesterday. There is a bit less color, but the problem still persists

![image](https://user-images.githubusercontent.com/15271049/216171261-9b90625e-1e53-41c5-9bd7-d44b641fb7d2.png)

**Comment by Austinauth** [comment]
@rajeshkamal5050 Do you know who on your team is working on the colors? I think we just need to sit down together and quickly work through this.

**Comment by rajeshkamal5050** [comment]
> @rajeshkamal5050 Do you know who on your team is working on the colors? I think we just need to sit down together and quickly work through this.

Please work with @vhvb1989

**Comment by rajeshkamal5050** [comment]
@vhvb1989 is this fixed?

**Comment by savannahostrowski** [comment]
I think that this is fixed - I recently had someone try this out and they had no complaints. I will close but please reopen if need be.
