### ISSUE TITLE
The web app fail to start ADE Integration test 

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#3767]
**Describe the issue:**
Test `todo-nodejs-mongo` template. After running `azd deploy`, click the web app link, get error as follow：
![image](https://github.com/Azure/azure-dev/assets/80496810/fc276778-31c0-4d7f-aa35-7e9d34f82d64)
Azure portal log: 
![image](https://github.com/Azure/azure-dev/assets/80496810/320c494d-5bd7-4414-8011-bc0dcf1057c6)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Configure Devcenter in `azd` refer to https://github.com/Azure/azure-dev/pull/2767:
```
"platform": {
     "config": {
	  "name": "<devcenter-name>"
	},
      "type": "devcenter"
  }
```
3. Run `azd init -t todo-nodejs-mongo -b staging`, `azd provision` and `azd deploy`.

**Environment:**
- Template: todo-nodejs-mongo.
- OS: Windows
- Azd version : 1.9.0-beta.1-daily.3712265  (commit https://github.com/Azure/azure-dev/commit/2943ce04880029dcc48e82a52ff4e1070636f1da)

**Expected behavior:**
Run `azd deploy`, the web app can start successfully.

@rajeshkamal5050  for notification.

**Comment by wbreza** [comment]
@v-jiaodi - what is your ADE configuration?

**Comment by v-jiaodi** [comment]
@wbreza Sorry, I didn't express myself clearly here，I will update it as follows：
Configure Devcenter in `azd` refer to https://github.com/Azure/azure-dev/pull/2767:
```
"platform": {
     "config": {
	  "name": "<devcenter-name>"
	},
      "type": "devcenter"
  }
```

**Comment by wbreza** [comment]
This is failing because the ADE environment definitions were not updated when the app code migrated from CRA to VITE.
https://github.com/microsoft/devcenter-catalog/pull/90

cc @vhvb1989

**Comment by v-jiaodi** [comment]
@wbreza Retest, this issue still exist.

**Comment by rajeshkamal5050** [comment]
@v-jiaodi can you retest with an updated devcenter-catalog? Since the fix was on the devcenter side and not sure if they have rolled out - https://github.com/microsoft/devcenter-catalog/pull/90 cc @wbreza

**Comment by wbreza** [comment]
Resolved with https://github.com/microsoft/devcenter-catalog/pull/90

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 @wbreza  Retest with an updated devcenter-catalog, this issue still exists.
In the latest round of manual testing for azd, this issue still exists.
- Template: `todo-python-mongo`,`todo-nodejs-mongo`
- Branch: `staging`
- Azd version: `1.10.0-beta.1-daily.3792048`  (commit https://github.com/Azure/azure-dev/commit/13a7dd52710daa4ac5f0c17be6a77244005ac76e)

**Comment by v-jiaodi** [comment]
@wbreza Retest with  https://github.com/wbreza/devcenter-catalog/tree/appservice-updates, it works.
