### ISSUE TITLE
[Issue] Deployed Aspire Dashboard forces logging in using a school or work account

### ISSUE THREAD

**Issue by Kumima** [Azure/azure-dev#4010]
### Describe the bug
When trying to get access to the Aspire Dashboard deployed on Azure Container Apps. It uses Microsoft OIDC authentication, and it requires a school or work account to login. So, I can't enter the dashboard.

### To Reproduce
Following the official document to deploy the Aspire Starter Project on Azure Container Apps.

### Expected behavior
Personal account should work.

### Additional context
When I did tests weeks ago, it worked with my personal account. My azure subscription uses my personal account.

**Comment by rajeshkamal5050** [comment]
Don't think azd does anything special for the aca dashboard's authn @vhvb1989 should this be routed to aca dashboard team?

**Comment by vhvb1989** [comment]
yes, this needs to be followed up with ACA team. I'll let them know

**Comment by vhvb1989** [comment]
The fix for this rolled out after 6/17 (after this issue was opened).  This should be fixed by now.
Closing this.
Feel free to re-open if you can still repro

**Comment by Kumima** [comment]
@vhvb1989 I just retry. Creating new Aspire Starter Project -> azd init -> azd up, and nothing else. My azd version is 1.9.5. Still shows "Please use a school or work account."

**Comment by snehapar9** [comment]
@Kumima can you share your environment name? We will take a look.

**Comment by Kumima** [comment]
@snehapar9 Thanks for the support, I've sent the required info.

**Comment by snehapar9** [comment]
Thanks for contacting ACA Support @Kumima! We performed mitigation on your environment while working on a long-term solution. Can you please re-try and let us know if you can access the dashboard?

**Comment by Kumima** [comment]
@snehapar9 I succeed to get access the dashboard now. But this is just a default project template to indicate the issue. Please close #4121 when long-term solution is ready.

**Comment by davidebbo** [comment]
@snehapar9 this appears to be a somewhat common issue. See https://github.com/dotnet/aspire/discussions/4826. Since this one is closed, is there another one tracking the general fix?

I've emailed my sub/env details to get the mitigation. Thanks!

**Comment by snehapar9** [comment]
@davidebbo We performed mitigation on your environment. Please confirm you can access the dashboard.

**Comment by davidebbo** [comment]
Thank you @snehapar9, it does work great now!
