### ISSUE TITLE
Can not display option and select option when run `azd init` by GoLand

### ISSUE THREAD

**Issue by rujche** [Azure/azure-dev#4311]
**Describe the problem**
Can not display option and select option when run by [GoLand](https://www.jetbrains.com/go/)

**To Reproduce**
1. Use GoLand to open current project.
2. Run `cli/azd/main.go` by GoLand.
3. It outputs `Initializing an app to run on Azure (azd init)  How do you want to initialize your app? `, but no option displayed.

> ![image](https://github.com/user-attachments/assets/871425a1-083d-4361-8615-476cbc5ea902)

**Expected behavior**
Options displayed and can be selected.

**Environment**
Information on your environment:
 - **Language name and version**: go version go1.23.1 windows/amd64
 - **IDE and version**: GoLand 2024.2.1.1
 - **Device information**:
  > ![image](https://github.com/user-attachments/assets/5ce26105-13a1-47a0-9d55-40b4c1e0daeb)
 - **Go Settings in GoLand**:
  > ![image](https://github.com/user-attachments/assets/baba1c93-7c95-489b-b1be-4510c227501d)
  > ![image](https://github.com/user-attachments/assets/9bfd3127-f75f-4684-8ce1-8543bbd429d7)
  > ![image](https://github.com/user-attachments/assets/e030cc32-7949-4cf5-9802-ec2376ae8813)
  > ![image](https://github.com/user-attachments/assets/1a6f9802-482f-47ba-9a6e-a6363e6d54d4)

**Comment by weikanglim** [comment]
@rujche I haven't looked into how the `goland` terminal is implemented, but the auto-TTY detection behavior isn't working as expected. 

With #4318, we'll give you the ability to specify `AZD_FORCE_TTY=true` to ignore the terminal detection logic. The private build should be available for you to test soon. I'll reply back when that's available. 

If you have spare time and would love to help us, you can run the code snippet from the library we're using to investigate why the terminal detection logic isn't working as expected -- and what we may want to contribute upstream (issue or code) to fix this behavior.

```golang
package main

import (
	"fmt"
	"github.com/mattn/go-isatty"
	"os"
)

func main() {
	if isatty.IsTerminal(os.Stdout.Fd()) {
		fmt.Println("Is Terminal")
	} else if isatty.IsCygwinTerminal(os.Stdout.Fd()) {
		fmt.Println("Is Cygwin/MSYS2 Terminal")
	} else {
		fmt.Println("Is Not Terminal")
	}
}
```

**Comment by weikanglim** [comment]
@rujche Feel free to install a private [build](https://github.com/Azure/azure-dev/pull/4318#issuecomment-2353584262) and set `AZD_FORCE_TTY=true` to get it working in the Goland terminal.

**Comment by rujche** [comment]
Hi, @weikanglim 

Thanks for the reply.
I tried the code above here is the result:

> Is Not Terminal

Here is the related screenshot:
![image](https://github.com/user-attachments/assets/e13f9a0d-7596-49b0-81cf-f9ca23c3fc59)

**Comment by rujche** [comment]
> @rujche Feel free to install a private [build](https://github.com/Azure/azure-dev/pull/4318#issuecomment-2353584262) and set `AZD_FORCE_TTY=true` to get it working in the Goland terminal.

Hi, @weikanglim After adding the changed in your PR, it returns the new error:

> ![image](https://github.com/user-attachments/assets/d4305018-f305-4067-822f-99a4529837cc)

**Comment by weikanglim** [comment]
> After adding the changed in your PR, it returns the new error:

It looks like `AZD_FORCE_TTY` is taking effect, but you may hitting this issue in the [survey](https://github.com/AlecAivazis/survey/issues/148) library we're using in the terminal environment. Perhaps under the covers GoLand Terminal is using a MingW64 bash-for-windows-like variant. Unfortunately, fixing this would likely be along the times of a feature request along the lines of changing our UI library. I wish I had better news here...

Once thing that could help -- there's a new beta GoLand terminal that you could try [here](https://www.jetbrains.com/help/go/terminal-emulator.html#new-terminal). I'm not sure if they changed things underneath that could fix the experience here.

**Comment by rajeshkamal5050** [comment]
Issue addressed via #4318

**Comment by rujche** [comment]
Here is current status:

1. After set `AZD_FORCE_TTY=true`, it returns error like this:

> ![Image](https://github.com/user-attachments/assets/e111d228-3dd4-4eea-9258-ab107622387c)

2. Even if I changed Terminal to Powershell and "Enabled New Terminal", this problem still exists:

> ![Image](https://github.com/user-attachments/assets/37350dc6-7514-4593-a936-fdc458b68448)

> ![Image](https://github.com/user-attachments/assets/b1251dcf-4de2-4f47-b476-74cd20ceba38)

**Comment by rujche** [comment]
Hi, @weikanglim 

1. I solved this problem by changing to VS Code.
2. Seems this problem is caused by survey library.
3. But it's not cause by https://github.com/AlecAivazis/survey/issues/148, because it still exists when I use PowerShell instead of Git Bash.
4. The survey library is no longer maintained, How about changing to the suggested library written in the readme?

> ![Image](https://github.com/user-attachments/assets/fbcbb504-dc7c-41b9-bfd0-f5f2f0ba7051)

**Comment by weikanglim** [comment]
@rujche just curious, are you using Windows PowerShell? Or `pwsh`? I do think we have users that are able to run `azd` there -- we haven't heard this being reported widely.

**Comment by rujche** [comment]
Hi, @weikanglim 
Thanks for the response.

### 1.  are you using Windows PowerShell? Or pwsh?

I'm using Windows + Go Land + (PowerShell or GitBash)
In my understand, In Go Land, the `Terminal` and `Run` are different:
1. `Terminal` is related to PowerShell or GitBash, and this can be configured.
2. `Run` is not related to PowerShell or GitBash.

Here are related screenshots:
1. `Run` window:
   > ![Image](https://github.com/user-attachments/assets/f394b4e7-f80d-4aa1-8434-75bd3bd59a12)
2. `Terminal` window:
   > ![Image](https://github.com/user-attachments/assets/8d15972e-d054-4cdf-99a1-b8b2914cb95e)
3. And the IDE setting can only change the `Terminal` windlow
   > ![Image](https://github.com/user-attachments/assets/0dbc7f12-2b69-428d-a38a-5f3897a96e30)

Correct me if my understanding is wrong.

### 2. I do think we have users that are able to run azd there -- we haven't heard this being reported widely.

Maybe this problem only happens when run in IDE, not happens when it compiled into an executable file (azd.exe)

This problem not only happened in my machine, it also happened in @haozhan's machine. You can install [GoLand](https://www.jetbrains.com/go/download/#section=windows) to have a try if you are using windows.

**Comment by weikanglim** [comment]
@rujche Thanks for the extra information. From the screenshots, it seems like you are still running into the issue with Git Bash. I really doubt GoLand is doing anything weird here -- it's entirely due to the shell implementation. I'm not entirely sure what I'd recommend here -- for what it's worth, in my workflow I run a WSL container + VSCode to get `bash` and other GNU utilities while running on a Windows desktop.

I was really interested in the earlier response you had provided: 

> But it's not cause by https://github.com/AlecAivazis/survey/issues/148, because it still exists when I use PowerShell instead of Git Bash.

If this is happening, do share a screenshot of this. 

But I suspect that we're ultimately coming back to https://github.com/AlecAivazis/survey/issues/148 and migrating to other UI libraries are indeed something we're thinking about -- but it's a big feature ask that will need to be done separately outside of this bug report. We will gladly test out MINGW64 scenarios if we ever do such a work.

**Comment by rujche** [comment]
Hi, @weikanglim 
Thanks for the quick response.

### 1. it seems like you are still running into the issue with Git Bash

Not related to Git Bash. Because this problem still exists when I changed Terminal to PowerShell. Here are related screenshots:

> ![Image](https://github.com/user-attachments/assets/c2ce56b5-08e0-4617-a238-f6bfb48f920a)

> ![Image](https://github.com/user-attachments/assets/d5fde479-268a-4842-a138-84178cd66718)

> ![Image](https://github.com/user-attachments/assets/97ba699c-5e94-4670-b11e-a405ebe66701)

### 2. I really doubt GoLand is doing anything weird here

I doubt in GoLand, the `Run` Console and the `Terminal` are not the same. The `Terminal` can be configured to use Git Bash or Powershell, but the Console can not be changed.

### 3. If this is happening, do share a screenshot of this.

> > But it's not cause by https://github.com/AlecAivazis/survey/issues/148, because it still exists when I use PowerShell instead of Git Bash.

> If this is happening, do share a screenshot of this.

Please see the screenshots above.

**Comment by spboyer** [comment]
Closing as stale — this issue has had no activity for 180+ days. If this is still relevant, please reopen with reproduction steps on the latest version of azd.
