### ISSUE TITLE
Cannot provision resources if Bicep template has Graph resources

### ISSUE THREAD

**Issue by Yvand** [Azure/azure-dev#4689]
**Output from `azd version`**
azd version 1.11.1 (commit ae08ceba17c7078c547df9ee5f97e9e7ceb2fe53)

**Describe the bug**
I use Bicep to create an app registration in Entra ID.
This requires to enable experimental features in Bicep, as described in https://learn.microsoft.com/en-us/graph/templates/quickstart-create-bicep-interactive-mode?tabs=CLI
The Bicep template works fine outside of azd.
But if I run `azd provision`, it fails with this error message:

```
ERROR: initializing provisioning manager: failed to compile bicep template: failed running bicep build: exit code: 1, stdout: , stderr: WARNING: The following experimental Bicep features have been enabled: Extensibility. Experimental features should be enabled for testing purposes only, as there are no guarantees about the quality or stability of these features. Do not enable these settings for any production usage, or your production environment may be subject to breaking.
/home/yvand/dev/repos/temp/azd-repro-bicepexp/infra/main.bicep(10,7) : Warning no-unused-params: Parameter "location" is declared but never used. [https://aka.ms/bicep/linter/no-unused-params]
/home/yvand/dev/repos/temp/azd-repro-bicepexp/infra/main.bicep(13,29) : Error BCP104: The referenced module has errors.
/home/yvand/dev/repos/temp/azd-repro-bicepexp/infra/entraid-app.bicep(3,11) : Error BCP400: Fetching types from the registry requires enabling EXPERIMENTAL feature "ExtensionRegistry".
/home/yvand/dev/repos/temp/azd-repro-bicepexp/infra/entraid-app.bicep(11,26) : Error BCP029: The resource type is not valid. Specify a valid resource type of format "<types>@<apiVersion>".
/home/yvand/dev/repos/temp/azd-repro-bicepexp/infra/entraid-app.bicep(16,41) : Error BCP062: The referenced declaration with name "appRegistration" is not valid.
```

**To Reproduce**
I published a minimal repro of this issue in https://github.com/Yvand/azd-repro-bicepexp
To repro:
azd init Yvand/azd-repro-bicepexp
azd provision

**Expected behavior**
The Bicep template is processed successfully

**Comment by rajeshkamal5050** [comment]
@Yvand thanks for reporting. I think this is related to azd using older version of bicep CLI.
We just merged a PR to upgrade bicep - https://github.com/Azure/azure-dev/pull/4685

To validate,
- You can try with the PR bits - https://github.com/Azure/azure-dev/pull/4685#issuecomment-2581847504
- Or, the daily builds should be available in a couple of hours.

cc @pamelafox @vhvb1989

**Comment by ellismg** [comment]
> We just merged a PR to upgrade bicep - https://github.com/Azure/azure-dev/pull/4685

Another thing to note (and maybe helpful for future issue readers), we do support setting the environment varaible `AZD_BICEP_TOOL_PATH` to the full path to `bicep` (or on windows `bicep.exe`) which allows you to use a custom version of Bicep.  In the future, you can also download the latest bicep release and set this env-var to force `azd` to use a different version of Bicep and see if that helps.

**Comment by Yvand** [comment]
I set the environment variable AZD_BICEP_TOOL_PATH to the path to the latest version of bicep `0.32.4`, and I confirm it fixes the issue.
Thank you for your help

**Comment by ellismg** [comment]
Closing the issue based on @Yvand's feedback.  With #4685 this should be fixed out of the box with our next release.

**Comment by justinyoo** [comment]
I have the latest version of `azd` 1.11.1, with azure CLI 2.68.0 and bicep CLI 0.32.4 installed, but I still get the same error, when I run `azd up`
